---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

domain_name: "%{hiera('deployment_identifier')}.infrablocks.click"
public_zone_id: 'Z08829023L5IPIQBJOX63'
private_zone_id: 'Z0211739BXR21FNN139O'
